In [ ]:
# Import numpy as np and see the version
import numpy as np
np.__version__

'1.25.2'

In [ ]:
# How to create a 1D array? Create a 1D array of numbers from 0 to 9

a=np.arange(10)
print(a)
print(type(a))
print(a.dtype)


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64


In [ ]:
# How to create a boolean array? Create a 3×3 numpy array of all True’s
b=np.full((3,3),True,dtype=bool)
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
c=np.ones((3,3),dtype=bool)
c

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

numpy.full(shape, fill_value, dtype = None, order = ‘C’) : Return a new array with the same shape and type as a given array filled with a fill_value. The numpy.ones() function returns a new array of given shape and type, with ones. dtype is float by Default Data type of returned array.  

In [ ]:
# How to extract items that satisfy a given condition from 1D array? Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]


array([1, 3, 5, 7, 9])

In [ ]:
# How to replace items that satisfy a condition with another value in numpy array?
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
# How to replace items that satisfy a condition without affecting the original array?
arr=np.arange(10)
out=np.where(arr%2==1,-1,arr)
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# How to reshape an array? Convert a 1D array to a 2D array with 2 rows
arr=np.arange(10)
print(arr.shape)
a1=arr.reshape(2,-1)
print(a1)
print(a1.shape)

(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [ ]:
# How to stack two arrays vertically?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)
np.concatenate([a,b])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
# How to stack two arrays horizontally?
np.concatenate([a,b],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
# How to generate custom sequences in numpy without hardcoding?
# Create the following pattern without hardcoding. Use only numpy functions and the below input array
# array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])
print(a)
print(a.shape)

[1 2 3]
(3,)


In [ ]:
x=np.concatenate([a,a,a])
print(x)

[1 2 3 1 2 3 1 2 3]


In [ ]:
y=np.repeat(a,3)
print(y)

[1 1 1 2 2 2 3 3 3]


In [ ]:
np.hstack([y,x])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

The numpy.repeat() function repeats elements of the array. numpy.repeat(arr, repetitions, axis = None)

In [ ]:
# How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.unique(a[np.isin(a,b)])

array([2, 4])

In [ ]:
np.intersect1d(a,b)

array([2, 4])

numpy.intersect1d() function find the intersection of two arrays and return the sorted, unique values that are in both of the input arrays.

In [ ]:
# How to remove from one array those items that exist in another?
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [ ]:
np.delete(a,np.isin(a,b))

array([1, 2, 3, 4])

In [ ]:
a[~ np.isin(a,b)]

array([1, 2, 3, 4])

In [ ]:
# How to get the positions where elements of two arrays match?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

x=np.argwhere(a==b)
print(x)
print(type(x))
print(x.shape)

[[1]
 [3]
 [5]
 [7]]
<class 'numpy.ndarray'>
(4, 1)


In [ ]:
x=np.where(a==b)
print(x)
print(type(x))
print(x[0])
print(x[0].dtype)
#print(x.shape)

(array([1, 3, 5, 7]),)
<class 'tuple'>
[1 3 5 7]
int64


In [ ]:
# How to extract all numbers between a given range from a numpy array? Get all items between 5 and 10 from a
a = np.array([2, 6, 1, 9, 10, 3, 27])
l=(a>=5) & (a<=10)
a[l]


array([ 6,  9, 10])

In [ ]:
index=np.where((a>=5) & (a<=10))
print(index)
a[index]

(array([1, 3, 4]),)


array([ 6,  9, 10])

In [ ]:
index=np.where(np.logical_and(a>=5,a<=10))
print(index)
a[index]

(array([1, 3, 4]),)


array([ 6,  9, 10])

In [ ]:
# How to make a python function that handles scalars to work on numpy arrays?
# Convert the function maxx that works on two scalars, to work on two arrays.

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5

pair_max=np.vectorize(maxx,otypes=[float])


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)


array([6., 7., 9., 8., 9., 7., 5.])

NumPy vectorization involves performing mathematical operations on entire arrays, eliminating the need to loop through individual elements. It refers to performing element-wise operations on arrays.

In [ ]:
# How to swap two columns in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [ ]:
# How to swap two rows in a 2d numpy array?
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [ ]:
# How to reverse the rows of a 2D array?
arr[:,[2,1,0]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [ ]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [ ]:
# How to create a 2D array containing random floats between 5 and 10?
np.random.randint(5,10,(5,3))+np.random.rand(5,3)

array([[6.81080413, 7.06881087, 6.80983258],
       [7.30925027, 6.9377726 , 7.61875553],
       [8.91248818, 7.67129855, 7.69468913],
       [6.23936651, 6.00918643, 8.12663106],
       [9.18948121, 6.80960179, 8.15275323]])

In [ ]:
np.random.uniform(5,10,(5,3))

array([[7.34133488, 8.53445136, 7.28054489],
       [8.3383413 , 6.91441319, 9.61790213],
       [9.14262026, 8.54158214, 5.84110866],
       [5.65328288, 8.08537169, 8.58325864],
       [5.34828944, 9.84189869, 6.05471285]])

In [ ]:
# How to print only 3 decimal places in python numpy array?
rand_arr = np.random.random((5,3))
print(rand_arr)
np.round(rand_arr,3)

[[0.73694393 0.19157438 0.15938539]
 [0.0442767  0.30628793 0.28979178]
 [0.35398104 0.49665815 0.4346753 ]
 [0.96467146 0.48022582 0.3054719 ]
 [0.8199476  0.06971914 0.11514577]]


array([[0.737, 0.192, 0.159],
       [0.044, 0.306, 0.29 ],
       [0.354, 0.497, 0.435],
       [0.965, 0.48 , 0.305],
       [0.82 , 0.07 , 0.115]])

In [ ]:
# How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

In [ ]:
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [ ]:
# How to limit the number of items printed in output of numpy array?
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [ ]:
# How to print the full numpy array without truncating
import sys
np.set_printoptions(threshold=sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# How to import a dataset with numbers and texts keeping the text intact in python numpy?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa']], dtype=object)

In [ ]:
# How to extract a particular column from 1D array of tuples?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_1d[:4]

<ipython-input-90-13c8c53b447b>:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

In [ ]:
species=[row[4] for row in iris_1d]
species[:4]

[b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa']

In [ ]:
# How to convert a 1d array of tuples to a 2d numpy array?
iris_2d=np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [ ]:
# How to compute the mean, median, standard deviation of a numpy array?
print(iris_2d[0].mean(),iris_2d[0].std())
print(np.mean(iris_2d[0]),np.median(iris_2d[0]),np.std(iris_2d[0]))

2.55 1.8874586088176872
2.55 2.45 1.8874586088176872


In [ ]:
#How to normalize an array so the values range exactly between 0 and 1?
max,min=iris_2d[0].max(),iris_2d[0].min()
iris_2d[0]=(iris_2d[0]-min)/(max-min)
iris_2d[0][:3]

array([1.   , 0.   , 0.125])

In [ ]:
# How to compute the softmax score?
sepallength = np.array([float(row[0]) for row in iris])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [ ]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

In [ ]:
def softmax(x):
    e_x = np.exp(x)
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

[0.00222  0.001817 0.001488 0.001346 0.002008 0.002996 0.001346 0.002008
 0.001102 0.001817 0.002996 0.001644 0.001644 0.000997 0.00447  0.004044
 0.002996 0.00222  0.004044 0.00222  0.002996 0.00222  0.001346 0.00222
 0.001644 0.002008 0.002008 0.002453 0.002453 0.001488 0.001644 0.002996
 0.002453 0.003311 0.001817 0.002008 0.003311 0.001817 0.001102 0.00222
 0.002008 0.001218 0.001102 0.002008 0.00222  0.001644 0.00222  0.001346
 0.002711 0.002008 0.01484  0.008144 0.013428 0.003311 0.009001 0.004044
 0.007369 0.001817 0.009947 0.002453 0.002008 0.00494  0.005459 0.006033
 0.003659 0.010994 0.003659 0.00447  0.006668 0.003659 0.00494  0.006033
 0.007369 0.006033 0.008144 0.009947 0.01215  0.010994 0.005459 0.004044
 0.003311 0.003311 0.00447  0.005459 0.002996 0.005459 0.010994 0.007369
 0.003659 0.003311 0.003311 0.006033 0.00447  0.002008 0.003659 0.004044
 0.004044 0.006668 0.00222  0.004044 0.007369 0.00447  0.016401 0.007369
 0.009001 0.02704  0.001817 0.020032 0.010994 0.01812

The softmax function is a function that turns a vector of K real values into a vector of K real values that sum to 1. The input values can be positive, negative, zero, or greater than one, but the softmax transforms them into values between 0 and 1, so that they can be interpreted as probabilities.

e^Zi/(sigma j=1 to k e^Zj)

Used in neural networks in multiclass classification.

In [ ]:
# How to find the percentile scores of a numpy array?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [ ]:
np.quantile(sepallength,[.5,.95])

array([5.8  , 7.255])

In [ ]:
np.percentile(sepallength,[5,95])

array([4.6  , 7.255])

 Percentiles are given as percent values, values such as 95%, 40%, or 27%. Quantiles are given as decimal values, values such as 0.95, 0.4, and 0.27.

In [ ]:
# How to insert values at random positions in an array?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

In [ ]:
print(iris_2d.shape)
iris_2d[:6]

(150, 5)


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa']], dtype=object)

In [ ]:
np.random.seed(100)
iris_2d[np.random.randint(150,size=20),np.random.randint(5,size=20)]=np.nan
iris_2d[:10]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', nan, b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa']], dtype=object)

In [ ]:
i,j=np.where(iris_2d)
print(i,j)
print(type(i))

[  0   0   0   0   0   1   1   1   1   1   2   2   2   2   2   3   3   3
   3   3   4   4   4   4   4   5   5   5   5   5   6   6   6   6   6   7
   7   7   7   7   8   8   8   8   8   9   9   9   9   9  10  10  10  10
  10  11  11  11  11  11  12  12  12  12  12  13  13  13  13  13  14  14
  14  14  14  15  15  15  15  15  16  16  16  16  16  17  17  17  17  17
  18  18  18  18  18  19  19  19  19  19  20  20  20  20  20  21  21  21
  21  21  22  22  22  22  22  23  23  23  23  23  24  24  24  24  24  25
  25  25  25  25  26  26  26  26  26  27  27  27  27  27  28  28  28  28
  28  29  29  29  29  29  30  30  30  30  30  31  31  31  31  31  32  32
  32  32  32  33  33  33  33  33  34  34  34  34  34  35  35  35  35  35
  36  36  36  36  36  37  37  37  37  37  38  38  38  38  38  39  39  39
  39  39  40  40  40  40  40  41  41  41  41  41  42  42  42  42  42  43
  43  43  43  43  44  44  44  44  44  45  45  45  45  45  46  46  46  46
  46  47  47  47  47  47  48  48  48  48  48  49  4

In [ ]:
np.random.seed(100)
iris_2d[np.random.choice(i,20),np.random.choice(j,20)]=np.nan
iris_2d[:10]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', nan, b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa']], dtype=object)

In [ ]:
# How to find the position of missing values in numpy array?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [ ]:
np.isnan(iris_2d[:,0]).sum()

5

In [ ]:
np.where(np.isnan(iris_2d[:,0]))

(array([13, 17, 47, 53, 91]),)

In [ ]:
# How to filter a numpy array based on two or more conditions?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
iris_2d[(iris_2d[:,0]<5.0) & (iris_2d[:,2]>1.5)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [ ]:
# How to drop rows that contain a missing value from a numpy array?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
iris_2d[np.sum(np.isnan(iris_2d),axis=1)==0][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
np.sum(np.isnan(iris_2d),axis=1)==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

arr : input array.
axis : axis along which we want to calculate the sum value. Otherwise, it will consider arr to be flattened(works on all the axis). axis = 0 means along the column and axis = 1 means working along the row.

In [ ]:
any_nan_in_row=np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
# How to find if a given array has any null values?
np.sum(np.isnan(iris_2d))

0

In [ ]:
np.isnan(iris_2d).any()

False

In [ ]:
# How to replace all missing values with 0 in a numpy array?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [ ]:
np.isnan(iris_2d)[:5]

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
iris_2d[np.isnan(iris_2d)]=0
iris_2d[:5]

array([[5.1, 0. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
# How to find the count of unique values in a numpy array?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [ ]:
print(type(iris[:,4]))
#species=np.array([row.tolist()[4] for row in iris])
species=iris[:,4]
np.unique(species,return_counts=True)

<class 'numpy.ndarray'>


(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object),
 array([50, 50, 50]))

In [ ]:
# How to find the correlation between two columns of a numpy array?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
np.corrcoef(iris[:,0],iris[:,2])[0,1]

0.8717541573048718

In [ ]:
from scipy.stats.stats import pearsonr
corr,p_value=pearsonr(iris[:,0],iris[:,2])
print(corr,p_value)

0.8717541573048713 1.0384540627941024e-47


<ipython-input-37-7cab4a129c01>:1: DeprecationWarning: Please use `pearsonr` from the `scipy.stats` namespace, the `scipy.stats.stats` namespace is deprecated.
  from scipy.stats.stats import pearsonr


In [ ]:
# How to convert a numeric to a categorical (text) array?
petallength=iris[:,2].astype('float64')
print(type(petallength))
print(type(petallength[0]))
print(np.min(petallength),np.max(petallength))
bin_edges=[0,3,5,10]
petal_bin=np.digitize(petallength,bin_edges)
petal_bin

<class 'numpy.ndarray'>
<class 'numpy.float64'>
1.0 6.9


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
labels={1:'small',2:'medium',3:'large'}
labelling=lambda x:labels[x]
fun=np.vectorize(labelling)
fun(petal_bin)

array(['small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium', 'large', 'medium',
       'medium', 'medium', 'medium', 'medium', 'large', 'medium',
       'medium', 'medium', 'medium', 'medium', 'medium', 'medium',
       'medium', 'medium', 'medium', 'medium

In [ ]:
petal_length_cat=np.array([labels[x] for x in petal_bin])
petal_length_cat[:4]

array(['small', 'small', 'small', 'small'], dtype='<U6')

In [ ]:
# How to create a new column from existing columns of a numpy array?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
print(iris_2d.shape)
iris_2d[:3]

(150, 5)


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [ ]:
import math
vol=lambda x: (math.pi*x[2]*x[0]**2)/3
v=np.array([vol(row[:3].astype('float64')) for row in iris_2d])
v[:4]



array([38.13265163, 35.20049849, 30.07237208, 33.23805027])

In [ ]:
sepallength=iris_2d[:,0].astype('float64')
petallength=iris_2d[:,2].astype('float64')
volume=(np.pi*petallength*sepallength**2)/3
print(volume.shape)

(150,)


In [ ]:
volume=volume[:,np.newaxis]
print(volume.shape)

(150, 1)


In [ ]:
out=np.hstack([iris_2d,volume])
print(out.shape)
out[:4]

(150, 6)


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004]], dtype=object)

numpy.newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array

4D array will become 5D array

and so on..

np.newaxis might come in handy when you want to explicitly convert a 1D array to either a row vector or a column vector.

A.shape from (4,) <= 1 dimensional to row vector (1,4) or column vector (4,1)

In [ ]:
# How to do probabilistic sampling in numpy?
# Randomly sample iris's species such that setose is twice the number of versicolor and virginica

# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
np.random.seed(100)
species=iris[:,4]
a=np.array(['Iris-setosa','Iris-versicolor','Iris-virginica'])
species_out=np.random.choice(a,150,p=[0.5,0.25,0.25])
species_out[:5]

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa'], dtype='<U15')

In [ ]:
# How to get the second largest value of an array when grouped by another array?
# What is the value of second longest petallength of species setosa
petallength=iris[iris[:,4]==b'Iris-setosa'][:,2].astype('float64')
petallength[:4]

array([1.4, 1.4, 1.3, 1.5])

In [ ]:
np.unique(np.sort(petallength))[-2]

1.7

In [ ]:
# How to sort a 2D array by a column
np.sort(iris[:,0])[:3]

array([b'4.3', b'4.4', b'4.4'], dtype=object)

In [ ]:
ind=np.argsort(iris[:,0]).tolist()
ind[:2]

[13, 42]

In [ ]:
sorted_iris=iris[ind,:]
sorted_iris[:2]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [ ]:
iris[iris[:,0].argsort()][:5]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa']], dtype=object)

In [ ]:
# How to find the most frequent value in a numpy array?
print(type(np.unique(iris[:,3],return_counts=True)))
val,count=np.unique(iris[:,3],return_counts=True)
print(val)
print(count)
val[np.argmax(count)]

<class 'tuple'>
[b'0.1' b'0.2' b'0.3' b'0.4' b'0.5' b'0.6' b'1.0' b'1.1' b'1.2' b'1.3'
 b'1.4' b'1.5' b'1.6' b'1.7' b'1.8' b'1.9' b'2.0' b'2.1' b'2.2' b'2.3'
 b'2.4' b'2.5']
[ 6 28  7  7  1  1  7  3  5 13  8 12  4  2 12  5  6  6  3  8  3  3]


b'0.2'

In [ ]:
# How to find the position of the first occurrence of a value greater than a given value?
np.argwhere(iris[:,3].astype('float')>1.0)[0]

array([50])

In [ ]:
# How to replace all values greater than a given value to a given cutoff?
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [ ]:
a>30

array([False, False, False,  True, False, False,  True,  True, False,
       False,  True, False, False, False, False,  True,  True, False,
        True, False])

In [ ]:
a<10

array([False, False, False, False,  True,  True, False, False,  True,
       False, False, False, False,  True, False, False, False,  True,
       False, False])

In [ ]:
a[a>30]=30
a

array([27.62684215, 14.64009987, 21.80136195, 30.        ,  1.23122395,
        6.95688692, 30.        , 30.        ,  7.69862289, 29.17957314,
       30.        , 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       30.        , 30.        ,  9.42510962, 30.        , 14.42961361])

In [ ]:
a[a<10]=10
a

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [ ]:
np.clip(a,a_min=10,a_max=30)

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [ ]:
np.where(a<10,10,np.where(a>30,30,a))

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [ ]:
# How to get the positions of top n values from a numpy array?
np.random.seed(100)
a=np.random.uniform(1,50,20)
print(a.shape)
a

(20,)


array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [ ]:
a.sort()
a

array([ 1.23122395,  6.31046763,  6.95688692,  7.69862289,  9.42510962,
       10.08108276, 11.25090398, 11.76517714, 14.42961361, 14.64009987,
       21.80136195, 27.62684215, 29.17957314, 33.86670515, 40.77247431,
       40.99501269, 41.466785  , 42.39403048, 44.67477576, 48.95256545])

In [ ]:
a[-5:]

array([40.99501269, 41.466785  , 42.39403048, 44.67477576, 48.95256545])

In [ ]:
np.sort(a)[-5:]

array([40.99501269, 41.466785  , 42.39403048, 44.67477576, 48.95256545])

In [ ]:
a[a.argsort()][-5:]

array([40.99501269, 41.466785  , 42.39403048, 44.67477576, 48.95256545])

In [ ]:
# How to compute the row wise counts of all possible values in an array?

dic={key:0 for key in range(1,11)}
dic

{1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0}

In [ ]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [ ]:
temp=[]
for row in arr:
  dic={key:0 for key in range(1,11)}
  for x in row:
    dic[x]+=1
  temp.append(list(dic.values()))

np.array(temp)

array([[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
       [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
       [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
       [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
       [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]])

In [ ]:
def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]

    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

counts_of_all_values_rowwise(arr)

<ipython-input-85-07792d926b82>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [ ]:
# How to convert an array of arrays into a flat 1d array?
arr1 = np.arange(3)
arr2 = np.arange(3,6)
arr3 = np.arange(7,10)

print(arr1.shape,arr2.shape,arr3.shape)
array_of_arrays = np.array([arr1, arr2, arr3])
print(array_of_arrays)

arr_1d=np.array([a for arr in array_of_arrays for a in arr])
arr_1d

(3,) (3,) (3,)
[[0 1 2]
 [3 4 5]
 [7 8 9]]


array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [ ]:
np.concatenate(array_of_arrays)

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

numpy.concatenate((arr1, arr2, …), axis=0, out=None)

Parameters :
arr1, arr2, … : [sequence of array_like] The arrays must have the same shape, except in the dimension corresponding to axis.

axis : [int, optional] The axis along which the arrays will be joined. If axis is None, arrays are flattened before use. Default is 0.

out : [ndarray, optional] If provided, the destination to place the result. The shape must be correct, matching that of what concatenate would have returned if no out argument were specified.

Return : [ndarray] The concatenated array.

In [ ]:
# How to generate one-hot encodings for an array in numpy?
np.random.seed(101)
arr = np.random.randint(1,4, size=6)
len(arr)

6

In [ ]:
encoding=[[0,0,0] for _ in range(len(arr))]
for i,x in enumerate(arr):
  encoding[i][x-1]=1

np.array(encoding).astype('float')


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
def one_hot_encoding(arr):
  uniques=np.unique(arr)
  encoding=np.zeros((arr.shape[0],uniques.shape[0]))
  for i,k in enumerate(arr):
    encoding[i,k-1]=1
  return encoding

one_hot_encoding(arr)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
# How to create row numbers grouped by a categorical variable?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [ ]:
print([i for val in np.unique(species_small) for i,grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5]


In [ ]:
# How to create groud ids based on a given categorical variable?
print([i for i,val in enumerate(np.unique(species_small)) for _ in enumerate(species_small[species_small==val])])

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


In [ ]:
# How to rank items in an array using numpy?
np.random.seed(10)
a = np.random.randint(20, size=10)
a

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [ ]:
a.argsort()

array([3, 9, 1, 7, 0, 8, 2, 5, 4, 6])

In [ ]:
a.argsort().argsort()

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

In [ ]:
dic={val:i+1 for i,val in enumerate(sorted(np.unique(a)))}
dic


{0: 1, 4: 2, 8: 3, 9: 4, 15: 5, 16: 6, 17: 7}

In [ ]:
f1=lambda x:dic[x]
f2=np.vectorize(f1)
f2(a)

array([4, 2, 5, 1, 7, 6, 7, 3, 4, 1])

In [ ]:
# How to rank items in a multidimensional array using numpy? Create a rank array of the same shape as a given numeric array a.
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [ ]:
np.concatenate(a).argsort().argsort().reshape((2,5))

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]])

In [ ]:
a.ravel().argsort().argsort().reshape((2,5))

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]])

In [ ]:
#How to find the maximum value in each row of a numpy array 2d?
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [ ]:
np.array([np.max(row) for row in a])

array([9, 8, 6, 3, 9])

In [ ]:
np.amax(a,axis=1)

array([9, 8, 6, 3, 9])

In [ ]:
np.apply_along_axis(np.max,arr=a,axis=1)

array([9, 8, 6, 3, 9])

In [ ]:
# How to compute the min-by-max for each row for a numpy array 2d?
f=lambda x:(np.min(x)/np.max(x))
np.apply_along_axis(f,arr=a,axis=1)           # df.apply(lambda x: np.min(x)/np.max(x), axis=1) , np.min(df, axis=1)/np.max(df, axis=1)

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

In [ ]:
np.array([np.min(row)/np.max(row) for row in a])

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

In [ ]:
# How to find the duplicate records in a numpy array?
np.random.seed(100)
a = np.random.randint(0, 5, 10)
a

array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

In [ ]:
s=set()
out=[]
for row in a:
  if row in s:
    out.append(True)
  else:
    out.append(False)
    s.add(row)

np.array(out)


array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

In [ ]:
out=np.full(a.shape[0],True)
unique_pos=np.unique(a,return_index=True)[1]
out[unique_pos]=False
out

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

In [ ]:
# How to find the grouped mean in numpy?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [ ]:
# How to drop all missing values from a numpy array?
x=np.array([1,2,3,np.nan,5,6,7,np.nan])
x

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

In [ ]:
x==np.nan

array([False, False, False, False, False, False, False, False])

np.nan is not comparable to np.nan. np.nan == np.nan gives False. nan is defined to not equal itself, therefore isnan() to check if an element is not a number.nan is not equal to anything.

In [ ]:
x[~np.isnan(x)]

array([1., 2., 3., 5., 6., 7.])

In [ ]:
# How to compute the euclidean distance between two arrays?
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
np.sqrt(np.sum((a-b)**2))

6.708203932499369

In [ ]:
np.linalg.norm(a-b)

6.708203932499369

In [ ]:
# How to find all the local maxima (or peaks) in a 1d array?
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
np.diff(a)

array([ 2,  4, -6,  1,  4, -6,  1])

In [ ]:
np.sign(np.diff(a))

array([ 1,  1, -1,  1,  1, -1,  1])

In [ ]:
doublediff=np.diff(np.sign(np.diff(a)))
doublediff

array([ 0, -2,  2,  0, -2,  2])

In [ ]:
peak_loc=np.where(doublediff==-2)[0]+1
peak_loc

array([2, 5])

In [ ]:
np.where(doublediff==-2)

(array([1, 4]),)

In [ ]:
# How to subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

In [ ]:
print(b_1d.T.shape)

(3,)


In [ ]:
print(b_1d.shape)

(3,)


It can transpose the 2-D arrays on the other hand it has no effect on 1-D arrays. This method transpose the 2-D numpy array.

In [ ]:
b=[1,2,3]
b_2d=np.array([b])
print(b_2d.shape)
b_2d

(1, 3)


array([[1, 2, 3]])

In [ ]:
print(b_2d.T.shape)
x=b_2d.T
x

(3, 1)


array([[1],
       [2],
       [3]])

In [ ]:
np.hstack([x,x,x])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
a_2d-np.hstack([x,x,x])

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
b_1d[:,None]

array([[1],
       [2],
       [3]])

In [ ]:
b_1d[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
a_2d-b_1d[:,np.newaxis]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
# How to find the index of n'th repetition of an item in an array. Find the index of 5th repetition of number 1 in x
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.where(x==1)[0][4]

8

argwhere returns the coordinates of where condition is True. In general, coordinates are tuples, therefore the output should be 2D. For consistency, this also applies to the case of 1D input.

In [ ]:
[i for i,v in enumerate(x) if v==1][4]

8

In [ ]:
#How to convert numpy's datetime64 object to datetime's datetime object?
dt64 = np.datetime64('2018-02-25 22:10:10')
print(type(dt64))

<class 'numpy.datetime64'>


In [ ]:
dt64.tolist()

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [ ]:
from datetime import datetime
dt64.astype(datetime)

datetime.datetime(2018, 2, 25, 22, 10, 10)

In [ ]:
# How to compute the moving average of a numpy array? moving average of window size 3.
np.random.seed(100)
Z = np.random.randint(10, size=10)
Z

array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])

In [ ]:
ret=np.cumsum(Z)
ret

array([ 8, 16, 19, 26, 33, 33, 37, 39, 44, 46])

In [ ]:
ret[3:]

array([26, 33, 33, 37, 39, 44, 46])

In [ ]:
ret[:-3]

array([ 8, 16, 19, 18, 17, 14, 11])

In [ ]:
ret[3:] = ret[3:] - ret[:-3]
ret

array([ 8, 16, 19, 18, 17, 14, 11,  6, 11,  9])

In [ ]:
print(ret.shape)

(10,)


In [ ]:
(ret[2:]/3).round(2)

array([6.33, 6.  , 5.67, 4.67, 3.67, 2.  , 3.67, 3.  ])

In [ ]:
# How to create a numpy array sequence given only the starting point, length and the step? length 10, starting from 5 and has a step of 3
start=5
step=3
n=10
end=start+(n*step)
np.arange(start,end,step)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [ ]:
# How to fill in missing dates in an irregular series of numpy dates?
dates=np.arange(np.datetime64('2018-02-01'),np.datetime64('2018-02-25'),2)
dates

array(['2018-02-01', '2018-02-03', '2018-02-05', '2018-02-07',
       '2018-02-09', '2018-02-11', '2018-02-13', '2018-02-15',
       '2018-02-17', '2018-02-19', '2018-02-21', '2018-02-23'],
      dtype='datetime64[D]')

In [ ]:
out=[]
for date,d in zip(dates,np.diff(dates)):
  out.append(np.arange(date,date+d))

filled_dates=np.array(out).reshape(-1)
final=np.hstack([filled_dates,dates[-1]])
final

array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

In [ ]:
# How to create strides from a given 1D array?
# From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

arr=np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
out=[]
window_len=4
stride=2
for i in range(0,len(arr)-window_len,stride):
  out.append(arr[i:i+window_len])
np.array(out)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

In [9]:
import numpy as np

x=np.random.randint(100)  ##  You can't call randint without any parameters.
y=np.random.randint(50,100) ## To generate number between 50 and 100. Lower bound inclusive upper bound exclusive
z=np.random.randint(100,size=(3)) ## Generate more than 1 value.
z1=np.random.randint(100,size=(3,2))  ## second param is size
print(x,"\n",y,"\n",z,"\n",z1)

31 
 66 
 [19 77 22] 
 [[48 49]
 [70 89]
 [71 28]]


In [7]:
## To generate float number between 0 and 1. shape of the array is the argument.
x=np.random.rand()
y=np.random.rand(5)
z=np.random.rand(3,2)
print(x,"\n",y,"\n",z)

0.0037199512243504262 
 [0.8231177  0.69294661 0.27363716 0.42548285 0.24830989] 
 [[0.42596689 0.66676096]
 [0.49548664 0.69395688]
 [0.04175045 0.59213078]]


In [17]:
# Return random number between 0.0 and 1.0
np.random.random(size=(3,2))

array([[0.97836167, 0.05444528],
       [0.49307556, 0.18969691],
       [0.68838677, 0.16852765]])

In [8]:
## To generate random number from array
x=np.random.choice([3,5,1,2,10])
y=np.random.choice([3,5,1,2,10],size=(3,2))
print(x,"\n",y)

3 
 [[2 2]
 [2 3]
 [3 1]]


In [11]:
# creates an array of specified shape and fills it with random values as per standard normal distribution
# normal (Gaussian) distribution of mean 0 and variance 1
x=np.random.randn()
y=np.random.randn(3,2)
z=np.random.randn(3,4,5)
print(x,"\n",y,"\n",z)

1.5423187432228633 
 [[ 0.5152052  -0.12571152]
 [ 1.24336862  1.09427089]
 [ 0.06877141 -1.36032691]] 
 [[[ 0.99685855 -0.18751922 -1.45085624  0.21372917  0.65352439]
  [ 0.90108974 -0.44516675  1.7918009   1.62290278 -0.01942078]
  [-1.17276199  0.01544697 -0.70840637  0.778047   -0.58652976]
  [-1.88646305  0.56151333  2.23604614 -0.67580064  0.86980232]]

 [[ 1.10431475  0.62402005 -0.79287151 -0.34185172  0.3400427 ]
  [-1.66243955 -0.54447582  0.42502365 -0.35530536  0.24674943]
  [ 0.83509556 -0.32795463 -0.48152882  0.46051044 -0.27411296]
  [ 0.18610693 -0.1927974   0.61406896  0.43006343  0.07383025]]

 [[ 2.32295421 -0.67752369  0.41601612 -0.81267449  1.9773967 ]
  [-0.16421844  0.5722524  -1.19107545 -0.1407581   0.53984838]
  [ 1.10539344 -1.27929704  1.32626238 -0.8743915  -0.23086708]
  [ 1.12812733  0.90073232  0.56457171  0.99810214  0.52667802]]]


In [12]:
## To get the random samples from uniform distribution
# Uniform Distribution is the probability distribution that represents equally likely outcomes - the probability of each outcome occurring is the same
x=np.random.uniform(2.5,5.5,10)   ##low,high,size
y=np.random.uniform(2.5,5.5,(3,2))
print(x,"\n",y)

[5.40439862 4.50873246 2.68694762 3.80087843 5.23046305 4.93540014
 4.95228473 5.20820516 5.09386731 4.01309621] 
 [[3.44517247 5.37965638]
 [3.59661654 4.21375363]
 [2.55430966 3.24018563]]


In [22]:
# Seed function is used to save the state of a random function
# so that it can generate same random numbers on multiple executions of the code on the same machine or on different machines

# The seed() method is used to initialize the random number generator.
# The random number generator needs a number to start with (a seed value) to be able to generate a random number.
# By default the random number generator uses the current system time.

np.random.seed(5)
x=np.random.random(10)

np.random.seed(5)
y=np.random.random(10)
print(x,"\n",y)

[0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386
 0.76590786 0.51841799 0.2968005  0.18772123] 
 [0.22199317 0.87073231 0.20671916 0.91861091 0.48841119 0.61174386
 0.76590786 0.51841799 0.2968005  0.18772123]


In [15]:
## To shuffle an array
arr=np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[7 1 6 9 4 0 8 2 5 3]
