# 20/03/2024 - Pandas Practice

In [1]:
#How to import pandas and check the version?
import pandas as pd
import numpy as np
pd.__version__

'1.5.3'

In [2]:
#How to create a series from a list, numpy array and dict?
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

s1=pd.Series(mylist)
s2=pd.Series(myarr)
s3=pd.Series(mydict)
print(s1.shape)
print(s1.dtype)
print(type(s1))


(26,)
object
<class 'pandas.core.series.Series'>


In [13]:
print(type(pd))
print(type(pd.core))
print(type(pd.core.series))
print(type(pd.core.series.Series))


<class 'module'>
<class 'module'>
<class 'module'>
<class 'type'>


In [14]:
print(s2.shape)
print(s2.dtype)
print(type(s2))
print(s3.shape)
print(s3.dtype)
print(type(s3))

(26,)
int64
<class 'pandas.core.series.Series'>
(26,)
int64
<class 'pandas.core.series.Series'>


In [15]:
print(s3)

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


In [16]:
print(s2)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int64


In [18]:
#How to convert the index of a series into a column of a dataframe?
print(s1.index)
print(s2.index)
print(s3.index)

RangeIndex(start=0, stop=26, step=1)
RangeIndex(start=0, stop=26, step=1)
Index(['a', 'b', 'c', 'e', 'd', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
       'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='object')


In [28]:
df1=pd.DataFrame(s1).reset_index()
df1.head()
print(type(df1))
print(df1.dtypes)

<class 'pandas.core.frame.DataFrame'>
index     int64
0        object
dtype: object


In [29]:
df2=pd.DataFrame(s3).reset_index()
df2.head()
print(type(df2))
print(df2.dtypes)

<class 'pandas.core.frame.DataFrame'>
index    object
0         int64
dtype: object


In [33]:
#df3=pd.DataFrame(s2,columns=['data']).reset_index()
df3=s2.to_frame(name='data').reset_index()
df3.head()

index  data
0      0     0
1      1     1
2      2     2
3      3     3
4      4     4

In [45]:
#How to combine many series to form a dataframe?
df4=pd.concat([s1,s2],ignore_index=True)
print(df4)
print(df4.dtypes)
print(type(df4))

0      a
1      b
2      c
3      e
4      d
5      f
6      g
7      h
8      i
9      j
10     k
11     l
12     m
13     n
14     o
15     p
16     q
17     r
18     s
19     t
20     u
21     v
22     w
23     x
24     y
25     z
26     0
27     1
28     2
29     3
30     4
31     5
32     6
33     7
34     8
35     9
36    10
37    11
38    12
39    13
40    14
41    15
42    16
43    17
44    18
45    19
46    20
47    21
48    22
49    23
50    24
51    25
dtype: object
object
<class 'pandas.core.series.Series'>


In [43]:
df5=pd.concat([s1,s2],axis=1,keys=["s1","s2"])
print(df5)
print(df5.dtypes)
print(type(df5))

   s1  s2
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25
s1    object
s2     int64
dtype: object
<class 'pandas.core.frame.DataFrame'>


In [46]:
df6=pd.DataFrame({'s1':s1,'s2':s2})
df6.head()

s1  s2
0  a   0
1  b   1
2  c   2
3  e   3
4  d   4

In [48]:
print(df6.dtypes)
print(type(df6))

s1    object
s2     int64
dtype: object
<class 'pandas.core.frame.DataFrame'>


In [58]:
#How to assign name to the series’ index?
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
ser.name="alphabets"
print(ser.head())
print(ser.index)

0    a
1    b
2    c
3    d
4    e
Name: alphabets, dtype: object
RangeIndex(start=0, stop=26, step=1)


In [62]:
ser.index.name="alphabets"
ser.head()

alphabets
0    a
1    b
2    c
3    d
4    e
Name: alphabets, dtype: object

In [66]:
#How to get the items of series A not present in series B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [69]:
print(ser1.isin(ser2))
print(ser2.isin(ser1))

0    False
1    False
2    False
3     True
4     True
dtype: bool
0     True
1     True
2    False
3    False
4    False
dtype: bool


In [73]:
pd.concat([ser1[~ser1.isin(ser2)],ser2[~ser2.isin(ser1)]],ignore_index=True) ## difference

0    1
1    2
2    3
3    6
4    7
5    8
dtype: int64

In [75]:
ser1[ser1.isin(ser2)]  ## intersection

3    4
4    5
dtype: int64

In [76]:
seru=pd.Series(np.union1d(ser1,ser2))
seri=pd.Series(np.intersect1d(ser1,ser2))
seru[~seru.isin(seri)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [77]:
#How to get the minimum, 25th percentile, median, 75th, and max of a numeric series?
ser = pd.Series(np.random.normal(10, 5, 25))
ser.describe()

count    25.000000
mean     11.742804
std       5.166596
min       1.372163
25%       9.762482
50%      12.454936
75%      15.092645
max      19.157270
dtype: float64

In [79]:
np.percentile(ser,q=[0,25,50,75,100])

array([ 1.37216319,  9.76248248, 12.45493623, 15.09264464, 19.15726996])

In [80]:
# How to get frequency counts of unique items of a series?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.head()

0    g
1    b
2    c
3    d
4    a
dtype: object

In [81]:
ser.nunique()

8

In [82]:
ser.unique()

array(['g', 'b', 'c', 'd', 'a', 'e', 'h', 'f'], dtype=object)

In [84]:
ser.value_counts()

a    7
b    5
c    4
g    3
d    3
h    3
f    3
e    2
dtype: int64

In [86]:
#How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
ser

0     4
1     2
2     3
3     4
4     4
5     3
6     1
7     4
8     2
9     3
10    3
11    4
dtype: int64

In [97]:
ser[~ser.isin(ser.value_counts().index[:2])]="Others"
ser

0          4
1     Others
2          3
3          4
4          4
5          3
6     Others
7          4
8     Others
9          3
10         3
11         4
dtype: object

In [9]:
import pandas as pd
import numpy as np
# How to bin a numeric series to 10 groups of equal size?
ser = pd.Series(np.random.random(20))
x=pd.cut(ser,10) #labels=["1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th"]
y=pd.qcut(ser,[0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1],labels=["1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th"])
print(x.value_counts())
x

(0.901, 0.995]     4
(0.237, 0.332]     3
(0.616, 0.711]     3
(0.806, 0.901]     3
(0.0462, 0.142]    2
(0.426, 0.521]     2
(0.332, 0.426]     1
(0.521, 0.616]     1
(0.711, 0.806]     1
(0.142, 0.237]     0
dtype: int64


0      (0.426, 0.521]
1      (0.237, 0.332]
2      (0.616, 0.711]
3      (0.901, 0.995]
4      (0.806, 0.901]
5      (0.616, 0.711]
6      (0.901, 0.995]
7      (0.426, 0.521]
8      (0.711, 0.806]
9      (0.806, 0.901]
10     (0.901, 0.995]
11     (0.806, 0.901]
12    (0.0462, 0.142]
13     (0.237, 0.332]
14     (0.521, 0.616]
15     (0.901, 0.995]
16    (0.0462, 0.142]
17     (0.616, 0.711]
18     (0.332, 0.426]
19     (0.237, 0.332]
dtype: category
Categories (10, interval[float64, right]): [(0.0462, 0.142] < (0.142, 0.237] < (0.237, 0.332] <
                                            (0.332, 0.426] ... (0.616, 0.711] < (0.711, 0.806] <
                                            (0.806, 0.901] < (0.901, 0.995]]

In [7]:
y.value_counts()

1st     2
2nd     2
3rd     2
4th     2
5th     2
6th     2
7th     2
8th     2
9th     2
10th    2
dtype: int64

In [10]:
z=pd.qcut(ser,10,labels=["1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th"])
z.value_counts()

1st     2
2nd     2
3rd     2
4th     2
5th     2
6th     2
7th     2
8th     2
9th     2
10th    2
dtype: int64

# pd.cut() and pd.qcut()

Qcut (quantile-cut) differs from cut in the sense that, in qcut, the number of elements in each bin will be roughly the same, but this will come at the cost of differently sized interval widths. On the other hand, in cut, the bin edges were equal sized (when we specified bins=3) with uneven number of elements in each bin or group. Also, cut is useful when you know for sure the interval ranges and the bins.

For example, if binning an ‘age’ column, we know infants are between 0 and 1 years old, 1-12 years are kids, 13-19 are teenagers, 20-60 are working class grownups, and 60+ senior citizens. So we can appropriately set bins=[0, 1, 12, 19, 60, 140] and labels=[‘infant’, ‘kid’, ‘teenager’, ‘grownup’, ‘senior citizen’]. In qcut, when we specify q=5, we are telling pandas to cut the Year column into 5 equal quantiles, i.e. 0-20%, 20-40%, 40-60%, 60-80% and 80-100% buckets/bins.

With qcut, we’re answering the question of “which data points lie in the first 15% of the data, or in the 51-78 percentile range etc.

In [15]:
# How to convert a numpy array to a dataframe of given shape?
# Reshape the series ser into a dataframe with 7 rows and 5 columns
ser = pd.Series(np.random.randint(1, 10, 35))
print(ser.index)
print(ser.values)

RangeIndex(start=0, stop=35, step=1)
[9 4 9 5 1 5 3 9 7 7 6 7 8 7 2 1 6 3 5 1 1 5 8 5 8 4 4 1 1 2 3 2 6 4 5]


In [16]:
df=ser.values.reshape((7,5))
df

array([[9, 4, 9, 5, 1],
       [5, 3, 9, 7, 7],
       [6, 7, 8, 7, 2],
       [1, 6, 3, 5, 1],
       [1, 5, 8, 5, 8],
       [4, 4, 1, 1, 2],
       [3, 2, 6, 4, 5]])

In [19]:
print(df.shape)
print(type(df))
df1=pd.DataFrame(df)
print(df1.shape)
print(type(df1))

(7, 5)
<class 'numpy.ndarray'>
(7, 5)
<class 'pandas.core.frame.DataFrame'>


In [21]:
df2=pd.DataFrame(ser)
print(type(df2))
print(df2.shape)

<class 'pandas.core.frame.DataFrame'>
(35, 1)


In [23]:
#How to find the positions of numbers that are multiples of 3 from a series?
ser = pd.Series(np.random.randint(1, 10, 7))
ser

0    6
1    6
2    6
3    1
4    3
5    1
6    8
dtype: int64

In [24]:
x=ser[ser.values%3==0].index
print(list(x))

[0, 1, 2, 4]


In [25]:
## argwhere to get indices of elements satisfying condition
print(ser)
z=np.argwhere(ser.to_numpy()%3==0)
print(z)
print(type(z))
print(z.shape)

0    6
1    6
2    6
3    1
4    3
5    1
6    8
dtype: int64
[[0]
 [1]
 [2]
 [4]]
<class 'numpy.ndarray'>
(4, 1)


In [28]:
np.where(ser%3==0)[0].tolist()

[0, 1, 2, 4]

In [44]:
#How to extract items at given positions from a series
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

ser.iloc[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [45]:
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [53]:
# How to stack two series vertically and horizontally ?
ser1=pd.Series(range(6))
ser2=pd.Series(list('abcde'))
print(ser1)
print(ser2)

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64
0    a
1    b
2    c
3    d
4    e
dtype: object


In [54]:
x=pd.concat([ser1,ser2],ignore_index=True)
y=pd.concat([ser1,ser2],axis=1,keys=["ser1","ser2"])
print(x)
print(y)

0     0
1     1
2     2
3     3
4     4
5     5
6     a
7     b
8     c
9     d
10    e
dtype: object
   ser1 ser2
0     0    a
1     1    b
2     2    c
3     3    d
4     4    e
5     5  NaN


In [55]:
ser1.append(ser2)

<ipython-input-55-fced70fb11a8>:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ser1.append(ser2)


0    0
1    1
2    2
3    3
4    4
5    5
0    a
1    b
2    c
3    d
4    e
dtype: object

In [3]:
# How to get the positions of items of series A in another series B?
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

x=list(ser1[ser1.isin(ser2)].index)
x

[0, 4, 5, 8]

In [17]:
import pandas as pd
import numpy as np

[np.where(ser1==i)[0].tolist()[0] for i in ser2]

[5, 4, 0, 8]

In [13]:
x=np.where(ser1==5)
print(type(x))
print(x)
print(x[0])

<class 'tuple'>
(array([3]),)
[3]


In [21]:
[np.argwhere(ser1.to_numpy()==i)[0].tolist()[0] for i in ser2]

[5, 4, 0, 8]

# nonzero(a), where(a) and argwhere(a)

The NumPy argwhere() method finds indices of array elements that are not zero as a 2D array. The argwhere() method takes one argument:array - an array whose non-zero indices are to be found. The argwhere() method returns indices of elements that are non-zero as a 2D array. We can also use argwhere() to find the indices of elements that satisfy the given condition.

where gives the option to return from two different arrays. where is different from nonzero in the case when you wish to pick elements of from array a if some condition is True and from array b when that condition is False.



In [30]:
# How to compute the mean squared error on a truth and predicted series?
truth=pd.Series(range(10))
predicted=pd.Series(range(10))+np.random.random(10)
mse=np.mean((predicted-truth)**2)
mse

0.30884640741037556

In [45]:
# How to convert the first character of each element in a series to uppercase?
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
[x[0].upper()+x[1:] for x in ser]

['How', 'To', 'Kick', 'Ass?']

In [43]:
s1=ser.map(lambda x:x[0].upper()+x[1:])
print(s1)
print(type(s1))

0     How
1      To
2    Kick
3    Ass?
dtype: object
<class 'pandas.core.series.Series'>


In [46]:
#pd.Series([i.title() for i in ser])
ser=ser.map(lambda x:x.title())
ser

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [48]:
# How to calculate the number of characters in each word in a series?
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
ser.map(lambda x:len(x))

0    3
1    2
2    4
3    4
dtype: int64

In [12]:
import pandas as pd
import numpy as np
# How to compute difference of differences between consequtive numbers of a series?
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
for i in range(2):
  diff=[ser[i]-ser[i-1] for i in range(1,len(ser))]
  ser=pd.Series(diff)
  # print(ser)
print(ser)
np.concatenate([[np.nan,np.nan],ser.astype('int64')])

int64


array([nan, nan,  1.,  1.,  1.,  1.,  0.,  2.])

In [15]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
x=ser.diff()
print(x)
print(type(x))
print(x.dtype)

0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    8.0
dtype: float64
<class 'pandas.core.series.Series'>
float64


In [18]:
y=ser.diff().diff().tolist()
print(y)
print(type(y))

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]
<class 'list'>


# Series.diff(periods=1)

First discrete difference of element.
Calculates the difference of a Series element compared with another element in the Series (default is element in previous row). period=-1 will give diff with next row.

# dataframe.diff(periods, axis)

The diff() method returns a DataFrame with the difference between the values for each row and, by default, the previous row.
Which row to compare with can be specified with the periods parameter.
If the axis parameter is set to axes='columns', the method finds the difference column by column instead of row by row.

In [20]:
# How to convert a series of date-strings to a timeseries?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [42]:
# How to get the day of month, week number, day of year and day of week from a series of date strings?
ser = pd.Series(['01 Jan 2010', '02 Jan 2010','03 Jan 2010','04 Jan 2010','02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
ser=pd.to_datetime(ser)
ser

0   2010-01-01 00:00:00
1   2010-01-02 00:00:00
2   2010-01-03 00:00:00
3   2010-01-04 00:00:00
4   2011-02-02 00:00:00
5   2012-03-03 00:00:00
6   2013-04-04 00:00:00
7   2014-05-05 00:00:00
8   2015-06-06 12:20:00
dtype: datetime64[ns]

In [43]:
x=ser.dt.day
print(x)
print(type(x))
x.to_list()

0    1
1    2
2    3
3    4
4    2
5    3
6    4
7    5
8    6
dtype: int64
<class 'pandas.core.series.Series'>


[1, 2, 3, 4, 2, 3, 4, 5, 6]

In [44]:
print(ser.dt.week.to_list())
print(ser.dt.day_of_year.to_list())
print(ser.dt.day_name().to_list())

[53, 53, 53, 1, 5, 9, 14, 19, 23]
[1, 2, 3, 4, 33, 63, 94, 125, 157]
['Friday', 'Saturday', 'Sunday', 'Monday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


<ipython-input-44-c6e98a108f3d>:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  print(ser.dt.week.to_list())


In [8]:
# How to convert year-month string to dates corresponding to the 4th day of the month?
import pandas as pd
import numpy as np
from datetime import timedelta
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
pd.to_datetime(ser).dt.date + timedelta(3)

0    2010-01-04
1    2011-02-04
2    2012-03-04
dtype: object

In [10]:
x=pd.to_datetime(ser).dt.date + pd.DateOffset(days=3)
x

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [14]:
print(x.astype(str))

0    2010-01-04
1    2011-02-04
2    2012-03-04
dtype: object


In [22]:
# 24. How to filter words that contain atleast 2 vowels from a series?
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
vow=set(['a','e','i','o','u'])

two_vowel_words=[]
for i,word in enumerate(ser.str.lower()):
    count=0
    for x in word:
        if x in vow:
            count+=1
        if count==2:
            two_vowel_words.append(i)
            break

ser[two_vowel_words]


0     Apple
1    Orange
4     Money
dtype: object

In [24]:
#How to filter valid emails from a series?

import re
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

mask=emails.map(lambda x:bool(re.match(pattern,x)))
emails[mask]

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

In [30]:
x=[re.match(pattern,email) for email in emails]
type(x[1])

re.Match

In [31]:
emails.str.findall(pattern, flags=re.IGNORECASE)

0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object

In [32]:
# How to get the mean of a series grouped by another series?

fruit=pd.Series(np.random.choice(['apple','banana','kiwi'],10))
weights=pd.Series(np.linspace(1,10,10))
print(list(fruit))
print(list(weights))

['apple', 'kiwi', 'kiwi', 'banana', 'apple', 'kiwi', 'banana', 'kiwi', 'apple', 'banana']
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]


In [33]:
weights.groupby(fruit).mean()

apple     5.00
banana    7.00
kiwi      4.75
dtype: float64

In [36]:
#How to compute the euclidean distance between two series?
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

round((sum((p-q)**2))**0.5,2)

18.17

In [37]:
np.linalg.norm(p-q)

18.16590212458495

In [54]:
# 28. How to find all the local maxima (or peaks) in a numeric series?
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
prevdiff=ser.diff()
print(type(prevdiff))
nextdiff=ser.diff(-1)
print(prevdiff,nextdiff)
cond=lambda x:x>0
print(ser[prevdiff.map(cond) & nextdiff.map(cond)].index)

ser.loc[prevdiff.map(cond) & nextdiff.map(cond)]

<class 'pandas.core.series.Series'>
0    NaN
1    8.0
2   -7.0
3    1.0
4    5.0
5    1.0
6   -8.0
7    5.0
8   -4.0
dtype: float64 0   -8.0
1    7.0
2   -1.0
3   -5.0
4   -1.0
5    8.0
6   -5.0
7    4.0
8    NaN
dtype: float64
Int64Index([1, 5, 7], dtype='int64')


1    10
5    10
7     7
dtype: int64

In [9]:
# How to replace missing spaces in a string with the least frequent character?
import pandas as pd
import numpy as np
my_str = 'dbc deb abed gade'
ser1=pd.Series(list(my_str))
print(type(ser1.value_counts().sort_values()))
s1=ser1.value_counts().sort_values()
ch=s1.index[0]

ch.join(my_str.split(" "))

<class 'pandas.core.series.Series'>


'dbccdebcabedcgade'

In [12]:
"".join(ser1.replace(' ',ch))

'dbccdebcabedcgade'

In [17]:
# How to create a TimeSeries starting ‘2000-01-01’ and 10 weekends (saturdays) after that having random numbers as values?
ser=pd.Series(np.random.randint(1,10,10),pd.date_range('2000-01-01',periods=10,freq='W-SAT'))
ser

2000-01-01    2
2000-01-08    5
2000-01-15    9
2000-01-22    6
2000-01-29    4
2000-02-05    9
2000-02-12    2
2000-02-19    3
2000-02-26    1
2000-03-04    3
Freq: W-SAT, dtype: int64

The date_range() function in Pandas for generating sequences of dates. It allows you to specify the starting date, ending date, frequency, and timezone for the generated dates,

In [13]:
# How to fill an intermittent time series so all missing dates show up with values of previous non-missing date?
import numpy as np
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

In [16]:
ser.resample('D').bfill().ffill() # fill next else prev value

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

Pandas dataframe.bfill() is used to backward fill the missing values in the dataset. It will backward fill the NaN values that are present in the pandas dataframe. Takes values from next row.

Pandas dataframe.resample() function is primarily used for time series data.
A time series is a series of data points indexed (or listed or graphed) in time order. Most commonly, a time series is a sequence taken at successive equally spaced points in time. It is a Convenience method for frequency conversion and resampling of time series. Object must have a datetime-like index (DatetimeIndex, PeriodIndex, or TimedeltaIndex), or pass datetime-like values to the on or level keyword.

W : weekly frequency
M : month end frequency
SM : semi-month end frequency (15th and end of month)
Q : quarter end frequency



In [17]:
# How to compute the autocorrelations of a numeric series?
# Compute autocorrelations for the first 10 lags of ser. Find out which lag has the largest correlation.
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
ser

0     -1.646286
1      6.106154
2      9.431520
3     -9.929554
4     -6.268050
5     -6.673207
6      3.269764
7     17.792048
8     12.308069
9     12.755106
10     3.071726
11     4.367268
12    25.756516
13     7.953454
14     9.731119
15    24.794218
16    31.297534
17    13.836694
18    13.522173
19     2.101566
dtype: float64

In [19]:
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations)
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

[1.0, 0.46, 0.15, 0.14, 0.12, 0.25, 0.18, 0.02, 0.35, 0.12, -0.01]
[0.46, 0.15, 0.14, 0.12, 0.25, 0.18, 0.02, 0.35, 0.12, -0.01]
Lag having highest correlation:  1


Autocorrelation represents the degree of similarity between a given time series and a lagged version of itself over successive time intervals.
Autocorrelation measures the relationship between a variable's current value and its past values.
An autocorrelation of +1 represents a perfect positive correlation, while an autocorrelation of -1 represents a perfect negative correlation.
Technical analysts can use autocorrelation to measure how much influence past prices for a security have on its future price.

In [20]:
# How to import only every nth row from a csv file to create a dataframe?
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:])
df2.head()

<ipython-input-20-2c85e7041674>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(chunk.iloc[0,:])
<ipython-input-20-2c85e7041674>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(chunk.iloc[0,:])
<ipython-input-20-2c85e7041674>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(chunk.iloc[0,:])
<ipython-input-20-2c85e7041674>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.append(chunk.iloc[0,:])
<ipython-input-20-2c85e7041674>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df2 = df2.appe

crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
50   0.08873  21.0   5.64   0.0  0.439  5.963  45.7  6.8147  4.0  243.0   
100  0.14866   0.0   8.56   0.0  0.520  6.727  79.9  2.7778  5.0  384.0   
150  1.65660   0.0  19.58   0.0  0.871  6.122  97.3  1.6180  5.0  403.0   
200  0.01778  95.0   1.47   0.0  0.403  7.135  13.9  7.6534  3.0  402.0   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45  19.7  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9

In [22]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()
df2.head()

crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
50   0.08873  21.0   5.64   0.0  0.439  5.963  45.7  6.8147  4.0  243.0   
100  0.14866   0.0   8.56   0.0  0.520  6.727  79.9  2.7778  5.0  384.0   
150  1.65660   0.0  19.58   0.0  0.871  6.122  97.3  1.6180  5.0  403.0   
200  0.01778  95.0   1.47   0.0  0.403  7.135  13.9  7.6534  3.0  402.0   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45  19.7  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9

In [23]:
# How to create a dataframe with rows as strides from a given series?

L = pd.Series(range(15))
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

In [24]:
# How to import only specified columns from a csv file?

#df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])


In [38]:
# How to get the nrows, ncolumns, datatype, summary stats of each column of a dataframe? Also get the array and list equivalent.
cars=pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv")
print(cars.shape)
print(type(cars))
print(cars.dtypes)
print(cars.dtypes.value_counts())
cars.describe()

(93, 27)
<class 'pandas.core.frame.DataFrame'>
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object
float64    18
object      9
dtype: int64


Min.Price      Price  Max.Price   MPG.city  MPG.highway  EngineSize  \
count  86.000000  91.000000  88.000000  84.000000    91.000000   91.000000   
mean   17.118605  19.616484  21.459091  22.404762    29.065934    2.658242   
std     8.828290   9.724280  10.696563   5.841520     5.370293    1.045845   
min     6.700000   7.400000   7.900000  15.000000    20.000000    1.000000   
25%    10.825000  12.350000  14.575000  18.000000    26.000000    1.800000   
50%    14.600000  17.700000  19.150000  21.000000    28.000000    2.300000   
75%    20.250000  23.500000  24.825000  25.000000    31.000000    3.250000   
max    45.400000  61.900000  80.000000  46.000000    50.000000    5.700000   

       Horsepower          RPM  Rev.per.mile  Fuel.tank.capacity  Passengers  \
count   86.000000    90.000000     87.000000           85.000000   91.000000   
mean   144.000000  5276.666667   2355.000000           16.683529    5.076923   
std     53.455204   605.554811    486.916616            3.375748    1.045953   
min     55.000000  3800.000000   1320.000000            9.200000    2.000000   
25%    100.750000  4800.000000   2017.500000           14.500000    4.000000   
50%    140.000000  5200.000000   2360.000000           16.500000    5.000000   
75%    170.000000  5787.500000   2565.000000           19.000000    6.000000   
max    300.000000  6500.000000   3755.000000           27.000000    8.000000   

           Length   Wheelbase      Width  Turn.circle  Rear.seat.room  \
count   89.000000   92.000000  87.000000    88.000000       89.000000   
mean   182.865169  103.956522  69.448276    38.954545       27.853933   
std     14.792651    6.856317   3.778023     3.304157        3.018129   
min    141.000000   90.000000  60.000000    32.000000       19.000000   
25%    174.000000   98.000000  67.000000    36.000000       26.000000   
50%    181.000000  103.000000  69.000000    39.000000       27.500000   
75%    192.000000  110.000000  72.000000    42.000000       30.000000   
max    219.000000  119.000000  78.000000    45.000000       36.000000   

       Luggage.room       Weight  
count     74.000000    86.000000  
mean      13.986486  3104.593023  
std        3.120824   600.129993  
min        6.000000  1695.000000  
25%       12.000000  2647.500000  
50%       14.000000  3085.000000  
75%       16.000000  3567.500000  
max       22.000000  4105.000000

In [43]:
df=cars.values
type(df)
df

array([['Acura', 'Integra', 'Small', ..., 2705.0, 'non-USA',
        'Acura Integra'],
       [nan, 'Legend', 'Midsize', ..., 3560.0, 'non-USA', 'Acura Legend'],
       ['Audi', '90', 'Compact', ..., 3375.0, 'non-USA', 'Audi 90'],
       ...,
       ['Volkswagen', 'Corrado', 'Sporty', ..., 2810.0, 'non-USA',
        'Volkswagen Corrado'],
       ['Volvo', '240', 'Compact', ..., 2985.0, 'non-USA', 'Volvo 240'],
       [nan, '850', 'Midsize', ..., 3245.0, 'non-USA', 'Volvo 850']],
      dtype=object)

In [45]:
cars.values.tolist()

[['Acura',
  'Integra',
  'Small',
  12.9,
  15.9,
  18.8,
  25.0,
  31.0,
  'None',
  'Front',
  '4',
  1.8,
  140.0,
  6300.0,
  2890.0,
  'Yes',
  13.2,
  5.0,
  177.0,
  102.0,
  68.0,
  37.0,
  26.5,
  nan,
  2705.0,
  'non-USA',
  'Acura Integra'],
 [nan,
  'Legend',
  'Midsize',
  29.2,
  33.9,
  38.7,
  18.0,
  25.0,
  'Driver & Passenger',
  'Front',
  '6',
  3.2,
  200.0,
  5500.0,
  2335.0,
  'Yes',
  18.0,
  5.0,
  195.0,
  115.0,
  71.0,
  38.0,
  30.0,
  15.0,
  3560.0,
  'non-USA',
  'Acura Legend'],
 ['Audi',
  '90',
  'Compact',
  25.9,
  29.1,
  32.3,
  20.0,
  26.0,
  'Driver only',
  'Front',
  '6',
  2.8,
  172.0,
  5500.0,
  2280.0,
  'Yes',
  16.9,
  5.0,
  180.0,
  102.0,
  67.0,
  37.0,
  28.0,
  14.0,
  3375.0,
  'non-USA',
  'Audi 90'],
 ['Audi',
  '100',
  'Midsize',
  nan,
  37.7,
  44.6,
  19.0,
  26.0,
  'Driver & Passenger',
  nan,
  '6',
  nan,
  172.0,
  5500.0,
  2535.0,
  nan,
  21.1,
  6.0,
  193.0,
  106.0,
  nan,
  37.0,
  31.0,
  17.0,
  3405.0,


In [47]:
# How to extract the row and column number of a particular cell with given criterion?
# Which manufacturer, model and type has the highest Price? What is the row and column number of the cell with the highest Price value?
cars=pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv")
cars.head(1)


Manufacturer    Model   Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra  Small       12.9   15.9       18.8      25.0   

   MPG.highway AirBags DriveTrain  ... Passengers  Length  Wheelbase  Width  \
0         31.0    None      Front  ...        5.0   177.0      102.0   68.0   

   Turn.circle Rear.seat.room  Luggage.room  Weight   Origin           Make  
0         37.0           26.5           NaN  2705.0  non-USA  Acura Integra  

[1 rows x 27 columns]

In [52]:
cars.loc[cars['Price']==cars['Price'].max(),['Manufacturer','Model','Type','Price']]

Manufacturer Model     Type  Price
58  Mercedes-Benz  300E  Midsize   61.9

In [59]:
x=cars.loc[cars['Price']==np.max(cars['Price'])]
row,col=np.where(cars.values==np.max(cars['Price']))
print(row,col)
print(type(row))

[58] [4]
<class 'numpy.ndarray'>


In [55]:
cars.values

array([['Acura', 'Integra', 'Small', ..., 2705.0, 'non-USA',
        'Acura Integra'],
       [nan, 'Legend', 'Midsize', ..., 3560.0, 'non-USA', 'Acura Legend'],
       ['Audi', '90', 'Compact', ..., 3375.0, 'non-USA', 'Audi 90'],
       ...,
       ['Volkswagen', 'Corrado', 'Sporty', ..., 2810.0, 'non-USA',
        'Volkswagen Corrado'],
       ['Volvo', '240', 'Compact', ..., 2985.0, 'non-USA', 'Volvo 240'],
       [nan, '850', 'Midsize', ..., 3245.0, 'non-USA', 'Volvo 850']],
      dtype=object)

In [56]:
np.where(cars['Price']==np.max(cars['Price']))

(array([58]),)

In [58]:
np.where(cars.iloc[58])            ## df.values retrieves cell. cars['col']-condition on column will retrieve row index.cars['row']- condition on row will retrieve all columns of that row

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26]),)

In [62]:
## retrieve value
print(cars.iat[row[0],col[0]])
print(cars.iloc[row[0],col[0]])

61.9
61.9


In [64]:
# Alternates
print(cars.at[row[0], 'Price'])

61.9


The difference between `iat` - `iloc` vs `at` - `loc` is:
`iat` snd `iloc` accepts row and column numbers.
Whereas `at` and `loc` accepts index and column names.

In [66]:
# How to rename a specific columns in a dataframe?
cars.columns
print(type(cars.columns))

<class 'pandas.core.indexes.base.Index'>


In [67]:
cars=cars.rename(columns={'Type':'CarType'})
cars.columns

Index(['Manufacturer', 'Model', 'CarType', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

In [68]:
cars.columns=cars.columns.map(lambda x:x.replace(".","-"))
cars.columns

Index(['Manufacturer', 'Model', 'CarType', 'Min-Price', 'Price', 'Max-Price',
       'MPG-city', 'MPG-highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev-per-mile', 'Man-trans-avail',
       'Fuel-tank-capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn-circle', 'Rear-seat-room', 'Luggage-room', 'Weight', 'Origin',
       'Make'],
      dtype='object')

In [101]:
# How to check if a dataframe has any missing values?
#How to count the number of missing values in each column?
x=cars.isna().sum()
print(type(x))
print(x.argmax())
print(x.iloc[x.argmax()])
print(list(x.index)[x.argmax()])

<class 'pandas.core.series.Series'>
23
19
Luggage-room


In [73]:
cars.isnull().sum()

Manufacturer           4
Model                  1
CarType                3
Min-Price              7
Price                  2
Max-Price              5
MPG-city               9
MPG-highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev-per-mile           6
Man-trans-avail        5
Fuel-tank-capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn-circle            5
Rear-seat-room         4
Luggage-room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [79]:
print(type(cars.isnull()))
print(type(cars.isnull().values))
cars.isnull().values.any()

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


True

In [105]:
#  How to replace missing values of multiple numeric columns with the mean?
df_out=cars[['Min-Price','Max-Price']]=cars[['Min-Price','Max-Price']].apply(lambda x:x.fillna(x.mean()))
df_out.isna().sum()

Min-Price    0
Max-Price    0
dtype: int64

In [108]:
# How to use apply function on existing columns with global variables as additional arguments?
d = {'Min-Price': np.nanmean, 'Max-Price': np.nanmedian}
df_out=cars[['Min-Price', 'Max-Price']] = cars[['Min-Price', 'Max-Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))
df_out.head()

Min-Price  Max-Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091

In [111]:
# How to select a specific column from a dataframe as a dataframe instead of a series?
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
print(type(df['a'].to_frame()))

<class 'pandas.core.frame.DataFrame'>


In [113]:
print(type(df[['a']]))
print(type(df.loc[:, ['a']]))
print(type(df.iloc[:, [0]]))
df.loc[:, ['a']].head()

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


a
0   0
1   5
2  10
3  15

In [115]:
# Alternately the following returns a Series
print(type(df.a))
print(type(df['a']))
print(type(df.loc[:, 'a']))
print(type(df.iloc[:, 0]))
df.iloc[:, 0]

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


0     0
1     5
2    10
3    15
Name: a, dtype: int64

In [116]:
# How to change the order of columns of a dataframe?
# In df, interchange columns 'a' and 'c'.
# Create a generic function to interchange two columns, without hardcoding column names.
# Sort the columns in reverse alphabetical order, that is colume 'e' first through column 'a' last.

df.head(2)

a  b  c  d  e
0  0  1  2  3  4
1  5  6  7  8  9

In [120]:
col=list(df)
print(col)
col[0],col[2]=col[2],col[0]
df.columns=col
df.head(2)

['a', 'b', 'c', 'd', 'e']


c  b  a  d  e
0  0  1  2  3  4
1  5  6  7  8  9

In [122]:
col.sort(reverse=True)
print(col)
df.columns=col
df.head(2)


['e', 'd', 'c', 'b', 'a']


e  d  c  b  a
0  0  1  2  3  4
1  5  6  7  8  9

In [124]:
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]

print(switch_columns(df,'b','d'))


    e   b   c   d   a
0   0   3   2   1   4
1   5   8   7   6   9
2  10  13  12  11  14
3  15  18  17  16  19


In [125]:
# How to set the number of rows and columns displayed in the output?
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)

In [129]:
# How to filter every nth row in a dataframe?
cars.iloc[::20,:][['Manufacturer','Model']]

Manufacturer    Model
0         Acura  Integra
20     Chrysler  LeBaron
40        Honda  Prelude
60      Mercury   Cougar
80       Subaru   Loyale

In [131]:
# How to create a primary key index by combining relevant columns?
cars[['Manufacturer','Model']]=cars[['Manufacturer','Model']].fillna('missing')

In [133]:
ind=cars['Manufacturer']+"-"+cars['Model']
cars.index=ind
cars.index[:5]

Index(['Acura-Integra', 'missing-Legend', 'Audi-90', 'Audi-100', 'BMW-535i'], dtype='object')

In [134]:
print(cars.index.is_unique)

True


In [3]:
# How to get the row number of the nth largest value in a column?
# Find the row position of the 5th largest value of column 'a' in df.
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
df


a   b   c
0  11   1  28
1  29   4  20
2   1  20  18
3  24  27  18
4  14  24  24
5   7  27  16
6  17  24   1
7  19  20  24
8  26  23   3
9  17  20   1

In [20]:
df['a'].argsort()[::-1][5]

9

In [9]:
# How to find the position of the nth largest value greater than a given value?
# In ser, find the position of the 2nd largest value greater than the mean.

ser = pd.Series(np.random.randint(1, 100, 15))
mean=ser.mean()
mean

45.333333333333336

In [15]:
ser[:10]

0    41
1    35
2    93
3    28
4    21
5    97
6    72
7    89
8    23
9     6
dtype: int64

In [30]:
np.argwhere(ser.to_numpy() > mean)[1]

array([5])

In [29]:
ser[ser>mean]

2     93
5     97
6     72
7     89
12    50
13    47
dtype: int64

In [31]:
# How to get the last n rows of a dataframe with row sum > 100
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

0   1   2   3
0   12  31  28  16
1   27  34  20  37
2   19  19  32  36
3   32  18  26  12
4   30  28  16  14
5   37  24  29  23
6   29  37  11  33
7   27  31  18  16
8   17  35  14  38
9   22  11  32  18
10  26  30  31  22
11  39  15  11  35
12  16  26  14  14
13  37  38  31  36
14  16  14  18  11

In [40]:
out=np.array([df.iloc[i] for i in range(len(df)) if np.sum(df.iloc[i])>100])
out[-2:]

array([[26, 30, 31, 22],
       [37, 38, 31, 36]])

In [48]:
rowsums=df.apply(np.sum,axis=1)
df.iloc[np.where(rowsums>100)][-2:]

0   1   2   3
10  26  30  31  22
13  37  38  31  36

In [17]:
# How to find and cap outliers from a series or dataframe column?
# Replace all values of ser in the lower 5%ile and greater than 95%ile with respective 5th and 95th %ile value.

ser = pd.Series(np.logspace(-2, 2, 30))
ser[:10]

0    0.010000
1    0.013738
2    0.018874
3    0.025929
4    0.035622
5    0.048939
6    0.067234
7    0.092367
8    0.126896
9    0.174333
dtype: float64

In [18]:
fifth=np.percentile(ser,5).round(6)
ninety_fifth=np.percentile(ser,95).round(6)
print(fifth,ninety_fifth)

0.016049 63.876672


In [19]:
low,high=np.percentile(ser,[5,95]).round(6)
print(low,high)

0.016049 63.876672


In [20]:
print(ser[ser<fifth])
print(ser[ser>ninety_fifth])

0    0.010000
1    0.013738
dtype: float64
28     72.789538
29    100.000000
dtype: float64


In [21]:
ser[ser<fifth]=fifth
ser[ser>ninety_fifth]=ninety_fifth

In [22]:
print(ser[ser<fifth])
print(ser[ser>ninety_fifth])

Series([], dtype: float64)
Series([], dtype: float64)


In [23]:
ser.loc[[0,1,28,29]]

0      0.016049
1      0.016049
28    63.876672
29    63.876672
dtype: float64

In [24]:
# How to reshape a dataframe to the largest possible square after removing the negative values?
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
df.head()

0   1   2   3   4   5   6   7   8   9
0  -3 -17 -15  35   3  10   6  -5  24  44
1  38  33 -17 -16  20  -9   3 -16   1 -16
2  10 -14 -19  22  24  24  29  11  48  -3
3  38  14  34  36   3  26 -20  10  26  11
4  -1 -14  27   6  -8  31  -9  40 -15  22

In [42]:
df1=df[df>0].values.flatten()
df1

array([nan, nan, nan, 35.,  3., 10.,  6., nan, 24., 44., 38., 33., nan,
       nan, 20., nan,  3., nan,  1., nan, 10., nan, nan, 22., 24., 24.,
       29., 11., 48., nan, 38., 14., 34., 36.,  3., 26., nan, 10., 26.,
       11., nan, nan, 27.,  6., nan, 31., nan, 40., nan, 22., 48., 47.,
       12., 44., nan, nan, nan, 33.,  3., 22., 24., nan,  4., nan, 42.,
       nan, 30.,  1.,  2., 34., nan, 40., 35., nan, 32., 27., nan, 28.,
       nan, 16., nan, 38., 38., 29., nan, nan, nan, 44., nan, nan, nan,
       nan, nan, 24., nan, 12.,  7., 10., 32.,  2.])

In [43]:
df2=df1[~ np.isnan(df1)]
print(type(df2))
print(df2)
print(len(df2))
df2.shape

<class 'numpy.ndarray'>
[35.  3. 10.  6. 24. 44. 38. 33. 20.  3.  1. 10. 22. 24. 24. 29. 11. 48.
 38. 14. 34. 36.  3. 26. 10. 26. 11. 27.  6. 31. 40. 22. 48. 47. 12. 44.
 33.  3. 22. 24.  4. 42. 30.  1.  2. 34. 40. 35. 32. 27. 28. 16. 38. 38.
 29. 44. 24. 12.  7. 10. 32.  2.]
62


(62,)

In [44]:
sq_len=int(np.floor(len(df2)**0.5))
sq_len

7

In [45]:
n_numbers=sq_len**2
indices=np.argsort(df2)[::-1][:n_numbers]
indices

array([17, 32, 33,  5, 55, 35, 41, 30, 46,  6, 18, 53, 52, 21,  0, 47, 20,
       45,  7, 36, 60, 48, 29, 42, 15, 54, 50, 49, 27, 25, 23,  4, 13, 14,
       56, 39, 38, 12, 31,  8, 51, 19, 34, 57, 16, 26, 24, 11,  2])

In [49]:
df2[sorted(indices)].reshape(sq_len,sq_len)

array([[35., 10., 24., 44., 38., 33., 20.],
       [10., 22., 24., 24., 29., 11., 48.],
       [38., 14., 34., 36., 26., 10., 26.],
       [11., 27., 31., 40., 22., 48., 47.],
       [12., 44., 33., 22., 24., 42., 30.],
       [34., 40., 35., 32., 27., 28., 16.],
       [38., 38., 29., 44., 24., 12., 32.]])

In [50]:
output=np.take(df2,sorted(indices)).reshape(sq_len,-1)
output

array([[35., 10., 24., 44., 38., 33., 20.],
       [10., 22., 24., 24., 29., 11., 48.],
       [38., 14., 34., 36., 26., 10., 26.],
       [11., 27., 31., 40., 22., 48., 47.],
       [12., 44., 33., 22., 24., 42., 30.],
       [34., 40., 35., 32., 27., 28., 16.],
       [38., 38., 29., 44., 24., 12., 32.]])

The numpy.take() function returns elements from array along the mentioned axis and indices.

In [64]:
# How to swap two rows of a dataframe? Swap rows 1 and 2
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [56]:
df[0],df[2]=df[2],df[0]    ## This does column swapping

In [53]:
df

0   1   2   3   4
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19
4  22  21  20  23  24

In [59]:
print(df[0])
print(df.loc[0])

0     2
1     7
2    12
3    17
4    22
Name: 0, dtype: int64
0    2
1    1
2    0
3    3
4    4
Name: 0, dtype: int64


In [61]:
df.loc[0],df.loc[2]=df.loc[2],df.loc[0]
df

0   1   2   3   4
0  12  11  10  13  14
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19
4  22  21  20  23  24

In [65]:
df.loc[0],df.loc[2]=df.loc[2].copy(),df.loc[0].copy()
df

0   1   2   3   4
0  10  11  12  13  14
1   5   6   7   8   9
2   0   1   2   3   4
3  15  16  17  18  19
4  20  21  22  23  24

In [63]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df)
temp=df.iloc[0].copy()
df.iloc[0]=df.iloc[2].copy()
df.iloc[2]=temp
df

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


0   1   2   3   4
0  10  11  12  13  14
1   5   6   7   8   9
2   0   1   2   3   4
3  15  16  17  18  19
4  20  21  22  23  24

In [68]:
# How to reverse the rows of a dataframe?
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [67]:
n_cols=df.shape[1]
for i in range(n_cols//2+1):
  df[i],df[n_cols-1-i]=df[n_cols-1-i],df[i]
df

0   1   2   3   4
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15
4  24  23  22  21  20

In [70]:
df.iloc[::-1,:]

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [71]:
df.iloc[:,::-1]

4   3   2   1   0
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15
4  24  23  22  21  20

In [72]:
# How to create one-hot encodings of a categorical variable (dummy variables)
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [73]:
df['a']

0     0
1     5
2    10
3    15
4    20
Name: a, dtype: int64

In [76]:
n=len(np.unique(df['a']))
print(n)
pd.get_dummies(df['a'])

5


0   5   10  15  20
0   1   0   0   0   0
1   0   1   0   0   0
2   0   0   1   0   0
3   0   0   0   1   0
4   0   0   0   0   1

In [77]:
pd.concat([pd.get_dummies(df['a']),df[list('bcde')]],axis=1)

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [78]:
# Which column contains the highest number of row-wise maximum values?
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
df.head()

0   1   2   3
0  16  79  62  17
1   7  95  92  78
2  59  80  72  11
3  97  56  89  44
4  20  69  88  99

In [79]:
np.argmax(df)

19

In [80]:
df.apply(np.argmax,axis=1)

0    1
1    1
2    1
3    0
4    3
5    3
6    3
7    1
8    0
9    3
dtype: int64

In [81]:
df.apply(np.argmax,axis=1).value_counts()

1    4
3    4
0    2
dtype: int64

In [84]:
df.apply(np.argmax,axis=1).value_counts().index[0]

1

In [85]:
# Create a new column such that, each row contains the row number of nearest row-record by euclidean distance.
nearest_rows = []
nearest_distance = []

# iterate rows.
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {}  # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance
df

0   1   2   3  nearest_row  dist
0  16  79  62  17            3    92
1   7  95  92  78            3   104
2  59  80  72  11            4    98
3  97  56  89  44            6   105
4  20  69  88  99            2    98
5  31  28  63  83            2    94
6  16  24  31  34            3   105
7  67  77  43  67            6    82
8  60  39  53  58            1    89
9  18  43  72  92            2    98

In [87]:
# Create a new column 'penultimate' which has the second largest value of each row of df
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
out=df.apply(lambda x:x.sort_values().unique()[-2],axis=1)
out

0    84
1    90
2    97
3    80
4    94
5    71
6    93
7    84
dtype: int64

In [88]:
df['penultimate']=out
df

0   1   2   3   4   5   6   7   8   9  penultimate
0  75  57  99  35  57  32  84  29  78  42           84
1  49  53  29  71  62  85  98  90  19  42           90
2   9  55  13  57  58  97  53  94  98  46           97
3  80  20  88   7  30  80  41  67  50  58           80
4  26  95  31  94  23  72  25  53  65  41           94
5  48  92  71  13  19  51  50  55   6  33           71
6   3  45  75  93  98  78  17  17  87  63           93
7  77   7  53  41   4  47  53  98  17  84           84

In [89]:
# How to normalize all columns in a dataframe?
# Normalize all columns of df by subtracting the column mean and divide by standard deviation.
# Range all columns of df such that the minimum value in each column is 0 and max is 1.

df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df

0   1   2   3   4   5   6   7   8   9
0  43  48  95  26  16  85  53  11  19   6
1  84   2  33  75  40  69  72  13  62  92
2  99  31  84  55  71  64  45  92  54  45
3  83  73   2  13  12  31   5  85  72  13
4  37  79  25   1  32  64  42  45  17  37
5  44  84  79  36  39  22  80  60   2  19
6  22   4  78  77  50  84  65   8  50  31
7  34  81  80  19  49  65  31  59  53  86

In [91]:
out=df.apply(lambda x:(x-x.mean())/x.std().round(2))
out

0         1         2         3         4         5         6  \
0 -0.447840 -0.065445  1.037102 -0.412425 -1.185175  1.076923  0.160389   
1  0.992273 -1.403432 -0.774175  1.307476  0.072027  0.373626  0.946813   
2  1.519143 -0.559919  0.715746  0.605476  1.695914  0.153846 -0.170737   
3  0.957148  0.661722 -1.679813 -0.868726 -1.394709 -1.296703 -1.826366   
4 -0.658588  0.836242 -1.007888 -1.289926 -0.347040  0.153846 -0.294909   
5 -0.412715  0.981675  0.569676 -0.061425  0.019644 -1.692308  1.277939   
6 -1.185458 -1.345259  0.540462  1.377676  0.595862  1.032967  0.657078   
7 -0.763962  0.894415  0.598890 -0.658126  0.543478  0.197802 -0.750207   

          7         8         9  
0 -1.070141 -0.884646 -1.091516  
1 -1.010063  0.834666  1.580951  
2  1.363022  0.514794  0.120416  
3  1.152749  1.234506 -0.873990  
4 -0.048813 -0.964614 -0.128185  
5  0.401772 -1.564374 -0.687539  
6 -1.160258  0.354858 -0.314636  
7  0.371733  0.474810  1.394500

In [92]:
out=df.apply(lambda x:(x.max()-x)/(x.max()-x.min()).round(2))
out

0         1         2         3         4         5         6  \
0  0.727273  0.439024  0.000000  0.671053  0.932203  0.000000  0.360000   
1  0.194805  1.000000  0.666667  0.026316  0.525424  0.253968  0.106667   
2  0.000000  0.646341  0.118280  0.289474  0.000000  0.333333  0.466667   
3  0.207792  0.134146  1.000000  0.842105  1.000000  0.857143  1.000000   
4  0.805195  0.060976  0.752688  1.000000  0.661017  0.333333  0.506667   
5  0.714286  0.000000  0.172043  0.539474  0.542373  1.000000  0.000000   
6  1.000000  0.975610  0.182796  0.000000  0.355932  0.015873  0.200000   
7  0.844156  0.036585  0.161290  0.763158  0.372881  0.317460  0.653333   

          7         8         9  
0  0.964286  0.757143  1.000000  
1  0.940476  0.142857  0.000000  
2  0.000000  0.257143  0.546512  
3  0.083333  0.000000  0.918605  
4  0.559524  0.785714  0.639535  
5  0.380952  1.000000  0.848837  
6  1.000000  0.314286  0.709302  
7  0.392857  0.271429  0.069767

In [98]:
# How to compute the correlation of each row with the suceeding row?
[df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0]-1)]

[-0.09, -0.04, 0.26, 0.32, 0.37, -0.19, -0.27]

In [99]:
# How to replace both the diagonals of dataframe with 0?
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0
df

0   1   2   3   4   5   6   7   8   9
0   0  48  95  26  16  85  53   0  19   6
1  84   0  33  75  40  69   0  13  62  92
2  99  31   0  55  71   0  45  92  54  45
3  83  73   2   0   0  31   5  85  72  13
4  37  79  25   0   0  64  42  45  17  37
5  44  84   0  36  39   0  80  60   2  19
6  22   0  78  77  50  84   0   8  50  31
7   0  81  80  19  49  65  31   0  53  86

In [105]:
# How to get the particular group of a groupby dataframe by key?
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])
df_grouped

In [101]:
df_grouped.get_group('apple')

col1      col2  col3
0  apple  0.932242     8
3  apple  0.335246    12
6  apple  0.858777     5

In [102]:
for i,dff in df_grouped:
  if i=='apple':
    print(dff)

    col1      col2  col3
0  apple  0.932242     8
3  apple  0.335246    12
6  apple  0.858777     5


<ipython-input-102-c068eb3784fd>:1: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for i,dff in df_grouped:


In [109]:
# How to get the n’th largest value of a column when grouped by another column?
# find the second largest value of 'taste' for 'banana'
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

In [110]:
df_grouped=df.groupby(['fruit'])
df_grouped

In [117]:
x=df_grouped.get_group('banana')['taste'].sort_values()[::-1]
print(type(x))
x

<class 'pandas.core.series.Series'>


1    0.986766
7    0.799291
4    0.597140
Name: taste, dtype: float64

In [119]:
x.iloc[1]

0.799291025055997

In [120]:
df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-2]

0.799291025055997

In [121]:
# How to compute grouped mean on pandas dataframe and keep the grouped column as another column (not index)?
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

In [123]:
df.groupby('fruit',as_index=False)['rating'].mean()

fruit    rating
0   apple  0.566802
1  banana  0.709200
2  orange  0.077169

In [124]:
# How to join two dataframes by 2 columns so they have only the common rows?
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

In [125]:
pd.merge(df1,df2,how='inner',left_on=['fruit','weight'],right_on=['pazham','kilo'],suffixes=['_left','_right'])

fruit weight  price_left  pazham  kilo  price_right
0   apple   high           1   apple  high           12
1   apple   high           4   apple  high           12
2   apple   high           8   apple  high           12
3  orange    low           1  orange   low            1
4  orange    low           7  orange   low            1
5  orange    low           1  orange   low            1

In [132]:
# How to remove rows from a dataframe that are present in another dataframe?
df1 = pd.DataFrame({'fruit': ['apple', 'orange', 'banana'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.arange(9)})

df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'weight': ['high', 'medium'] * 3,
                    'price': np.arange(6)})

In [137]:
df1[~ df1.isin(df2).all(axis=1)]

fruit  weight  price
2  banana     low      2
3   apple    high      3
4  orange  medium      4
5  banana     low      5
6   apple    high      6
7  orange  medium      7
8  banana     low      8

In [142]:
# How to get the positions where values of two columns match?
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
df

fruit1  fruit2
0  banana   apple
1   apple  orange
2  banana   apple
3   apple   apple
4  orange  orange
5   apple  banana
6   apple  banana
7   apple   apple
8   apple  banana
9  banana   apple

In [143]:
np.where(df['fruit1']==df['fruit2'])

(array([3, 4, 7]),)

In [145]:
#How to create lags and leads of a column in a dataframe?
# Create two new columns in df, one of which is a lag1 (shift column a down by 1 row) of column ‘a’ and the other is a lead1 (shift column b up by 1 row).
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))
df

a   b   c   d
0  19   4  72  89
1  28  86  30  64
2  75  91  12  92
3  99  39   8   1
4  30  63  93  84

In [146]:
df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
print(df)

    a   b   c   d  a_lag1  b_lead1
0  19   4  72  89     NaN     86.0
1  28  86  30  64    19.0     91.0
2  75  91  12  92    28.0     39.0
3  99  39   8   1    75.0     63.0
4  30  63  93  84    99.0      NaN


In [147]:
# How to get the frequency of unique values in the entire dataframe?
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
df

a  b  c  d
0  6  2  4  8
1  9  1  7  2
2  3  7  9  1
3  5  6  8  2
4  6  6  9  9

In [158]:
np.unique(df.values.flatten(),return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 3, 1, 1, 1, 4, 2, 2, 4]))

In [159]:
type(df.values.ravel())

numpy.ndarray

In [160]:
pd.value_counts(df.values.ravel())

6    4
9    4
2    3
8    2
1    2
7    2
4    1
3    1
5    1
dtype: int64

In [161]:
# How to split a text column into two separate columns?
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

print(df)

                          row
0          STD, City    State
1  33, Kolkata    West Bengal
2   44, Chennai    Tamil Nadu
3  40, Hyderabad    Telengana
4  80, Bangalore    Karnataka


In [171]:
data=df.apply(lambda x:x.str.split())
data

row
0           [STD,, City, State]
1  [33,, Kolkata, West, Bengal]
2   [44,, Chennai, Tamil, Nadu]
3   [40,, Hyderabad, Telengana]
4   [80,, Bangalore, Karnataka]

In [184]:
df_out=df['row'].str.split(',|\t',expand=True)
df_out

0                        1
0  STD            City    State
1   33   Kolkata    West Bengal
2   44    Chennai    Tamil Nadu
3   40   Hyderabad    Telengana
4   80   Bangalore    Karnataka

In [185]:
header=df_out.iloc[0]
df_out=df_out[1:]
df_out.columns=header
df_out

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka